/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gamedapbong;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.LineBorder;

/**
 *
 * @author tranv
 */
public class TrangChu extends javax.swing.JFrame {

    ArrayList<JLabel> dsBongBong = new ArrayList<>();
    int tongThoiGian = 30000;
    int thoiGianChoi = 0;
    int diem = 0;
    int randomNumberOld;
    int randomNumberNew;

    Thread threadRandomBong;
    Thread threadClick;

    /**
     * Creates new form TrangChu
     */
    public TrangChu() {
        initComponents();

        //khoiTaoDanhSachBongBong
        khoiTaoDanhSachBongBong();

    }

    public void khoiTaoDanhSachBongBong() {

        for (int i = 0; i < 100; i++) {
            ImageIcon icon = new ImageIcon(getClass().getResource("/resources/icon-bong.png"));
            JLabel lb = new JLabel();
            lb.setIcon(icon);
            lb.setCursor(new Cursor(Cursor.HAND_CURSOR));
            lb.setPreferredSize(new Dimension(30, 30));
            lb.setBorder(new LineBorder(Color.yellow));
            lb.setVisible(false);

            lb.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseClicked(MouseEvent e) {
                    if (threadClick != null && threadClick.isAlive()) {
                        threadClick.interrupt();
                    }

                    threadClick = new Thread(() -> {
                        System.out.println("goi ham");
                        lb.setVisible(false);
                        diem++;

                        lbDiem.setText("Điểm: " + diem);

                        if (thoiGianChoi > 0) {
                            randomBongBong();
                        }
                    });
                    threadClick.start();
                }

            });
            JPanel pn = new JPanel();
            pn.setLayout(new FlowLayout(FlowLayout.CENTER));
            pn.add(lb);

            pnListBong.add(pn);
            dsBongBong.add(lb);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnChoi = new javax.swing.JButton();
        lbDiem = new javax.swing.JLabel();
        pnListBong = new javax.swing.JPanel();
        lbThoiGian = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Game đập bóng");

        btnChoi.setText("Chơi");
        btnChoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChoiActionPerformed(evt);
            }
        });

        lbDiem.setText("Điểm: 0");

        pnListBong.setLayout(new java.awt.GridLayout(10, 10));

        lbThoiGian.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbThoiGian.setText("120");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnListBong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnChoi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbThoiGian, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbDiem)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnChoi)
                    .addComponent(lbDiem)
                    .addComponent(lbThoiGian))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnListBong, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChoiActionPerformed
        // TODO add your handling code here:
        countDown();
        randomBongBong();
         btnChoi.setEnabled(false);
    }//GEN-LAST:event_btnChoiActionPerformed

    public void randomBongBong() {

       

        Random random = new Random();
        int randomNumber = random.nextInt(100);
        while (randomNumberOld == randomNumber) {
            randomNumber = random.nextInt(100);
        }
        randomNumberOld = randomNumber;

        if (threadRandomBong != null && threadRandomBong.isAlive()) {
            threadRandomBong.interrupt();
        }
        
        threadRandomBong = new Thread(() -> {
            try {

                JLabel lb = (JLabel) dsBongBong.get(randomNumberOld);
                lb.setVisible(true);

                int tgSleep = thoiGianChoi * 1 / 20;
                System.out.println("tg sleep: "+tgSleep);
                Thread.sleep(tgSleep);

                lb.setVisible(false);

                if (thoiGianChoi > 0) {
                    randomBongBong();
                }

            } catch (InterruptedException ex) {
                if (!ex.getMessage().equals("sleep interrupted")) {
                    System.out.println(ex.getMessage());
                }
            }
        });
        threadRandomBong.start();

    }

    public void countDown() {
        if (thoiGianChoi != 0) {
            return;
        }

        thoiGianChoi = tongThoiGian;
        new Thread(() -> {
            while (true) {
                try {
                    Thread.sleep(1000);
                    thoiGianChoi -= 1000;
                    lbThoiGian.setText(String.valueOf(thoiGianChoi / 1000));

                    if (thoiGianChoi == 0) {
                        String mess = "Trò chơi kết thúc.\nTổng số điểm của bạn là: " + diem;
                        JOptionPane.showMessageDialog(null, mess);
                        btnChoi.setEnabled(true);

                        break;
                    }

                } catch (InterruptedException ex) {
                    System.out.println("Dung coutdown");
                    break;
                }
            }
        }).start();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChoi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbDiem;
    private javax.swing.JLabel lbThoiGian;
    private javax.swing.JPanel pnListBong;
    // End of variables declaration//GEN-END:variables
}
